---
---
# Source: azure-voting-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: azure-voting-app-azure-vote
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
type: Opaque
data:
  MYSQL_USER: "ZGJ1c2Vy"
  MYSQL_PASSWORD: "UGFzc3dvcmQxMg=="
  MYSQL_DATABASE: "YXp1cmV2b3Rl"
  MYSQL_HOST: "YXp1cmUtdm90aW5nLWFwcC1iYWNr"
  MYSQL_ROOT_PASSWORD: "UGFzc3dvcmQxMg=="
---

# Source: azure-voting-app/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-voting-app-mysql-pv-claim
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---

# Source: azure-voting-app/templates/azure-vote-back-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app-back
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql
  selector:
    app: azure-voting-app
    component: azure-voting-app-back
    release: azure-vote

---

# Source: azure-voting-app/templates/azure-vote-front-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app-front
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azure-voting-app
    component: azure-voting-app-front
    release: azure-vote
---

# Source: azure-voting-app/templates/azure-vote-back-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-voting-app-back
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
    component: azure-voting-app-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-voting-app
        heritage: "Tiller"
        release: "azure-vote"
        chart: azure-voting-app-0.1.0
        component: azure-voting-app-back
    spec:
      containers:
      - name: azure-voting-app-back
        image: "microsoft/azure-vote-back:v1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        args:
          - --ignore-db-dir=lost+found
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_DATABASE
        resources:
          {}
          
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: azure-voting-app-mysql-pv-claim
---

# Source: azure-voting-app/templates/azure-vote-front-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-voting-app-front
  labels:
    app: azure-voting-app
    heritage: "Tiller"
    release: "azure-vote"
    chart: azure-voting-app-0.1.0
    component: azure-voting-app-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-voting-app
        heritage: "Tiller"
        release: "azure-vote"
        chart: azure-voting-app-0.1.0
        component: azure-voting-app-front
    spec:
      containers:
      - name: azure-voting-app-front
        image: "hellorings/votingapp:7077"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: azure-voting-app-azure-vote
              key: MYSQL_HOST
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
          

